/**
 * Lista e lê transcripts de sessões do Claude CLI neste projeto.
 * Fonte: ~/.claude/projects/<pasta-codificada>/<session-id>.jsonl
 * (sessões --print não entram no picker interativo, mas ficam nestes arquivos).
 */
const fs = require('fs');
const os = require('os');
const path = require('path');

const LIMITE_PADRAO = 10;
const TITULO_MAX = 72;

/** Convenção do Claude: path do cwd com não-alfanuméricos virando `-`. */
function encodePath(caminho) {
  return path.resolve(caminho).replace(/[^a-zA-Z0-9]/g, '-');
}

function dirConfigClaude() {
  return process.env.CLAUDE_CONFIG_DIR
    ? path.resolve(process.env.CLAUDE_CONFIG_DIR)
    : path.join(os.homedir(), '.claude');
}

function dirProjeto(raiz) {
  return path.join(dirConfigClaude(), 'projects', encodePath(raiz));
}

function caminhoSessao(raiz, sessaoId) {
  const id = String(sessaoId || '').replace(/[^a-zA-Z0-9_-]/g, '');
  if (!id) throw new Error('ID de sessão inválido.');
  return path.join(dirProjeto(raiz), `${id}.jsonl`);
}

function extrairTextoDeConteudo(conteudo) {
  if (typeof conteudo === 'string') return limparTextoTranscricao(conteudo);
  if (!Array.isArray(conteudo)) return '';
  const bruto = conteudo
    .filter((b) => b && b.type === 'text' && typeof b.text === 'string')
    .map((b) => b.text)
    .join('\n');
  return limparTextoTranscricao(bruto);
}

/**
 * Skills cujo <command-args> é o pedido real do usuário (não um slash local
 * como /usage). O CLI grava /interface e /designer nesse envelope XML.
 */
const SKILLS_COM_PEDIDO_EM_ARGS = new Set(['interface', 'designer']);

const TAGS_RUIDO_CLI =
  'local-command-caveat|local-command-stdout|local-command-stderr|command-name|command-message|command-args|task-notification|ide_opened_file|ide_selection|ide_opened_selection|system-reminder';

/**
 * Remove ruído interno do Claude CLI que vaza no JSONL:
 * envelopes de slash commands locais (/usage etc.) e o prefixo /interface
 * que a própria interface injeta no início da conversa.
 *
 * Importante: em skills da interface o pedido do usuário fica em
 * <command-args>…</command-args>. Se apagarmos o bloco inteiro, o histórico
 * perde o título e cai no ID da sessão (ex.: "6f5a8f27").
 */
function limparTextoTranscricao(texto) {
  let t = String(texto || '');
  if (!t) return '';

  // Envelope de slash command (ordem message/name varia no JSONL).
  // /interface e /designer → preserva o pedido em command-args.
  // Demais (/usage, /context, …) → descarta.
  t = t.replace(
    /(?:<command-message>\s*[\s\S]*?\s*<\/command-message>\s*)?<command-name>\s*\/([\w-]+)\s*<\/command-name>\s*(?:<command-message>\s*[\s\S]*?\s*<\/command-message>\s*)?<command-args>([\s\S]*?)<\/command-args>/gi,
    (_, nome, args) => {
      const skill = String(nome || '').toLowerCase();
      if (SKILLS_COM_PEDIDO_EM_ARGS.has(skill)) return String(args || '').trim();
      return '';
    },
  );

  // Blocos internos restantes (caveats, task-notification, ide_*, etc.)
  t = t.replace(
    new RegExp(`<(${TAGS_RUIDO_CLI})\\b[^>]*>[\\s\\S]*?<\\/\\1>`, 'gi'),
    '',
  );
  // Tags órfãs / quebradas que ainda aparecem no UI
  t = t.replace(
    new RegExp(`<\\/?(?:${TAGS_RUIDO_CLI})\\b[^>]*>`, 'gi'),
    '',
  );

  // Texto do caveat sem as tags (fallback se o JSONL vier truncado/malformado)
  t = t.replace(
    /Caveat:\s*The messages below were generated by the user while running local commands\.[\s\S]*?unless the user explicitly asks you to\.?/gi,
    '',
  );

  // Envelope injetado pela interface (e /designer na galeria) — na UI ao vivo
  // o usuário não vê esses prefixos; no restore do transcript também não deve.
  t = t.replace(/^\/interface\b\s*/i, '');
  t = t.replace(/^\/designer\b\s*/i, '');
  // Contexto injetado na 1ª msg do canal site / tráfego.
  t = t.replace(/^\[Contexto da aba Site\][\s\S]*?\n\n/i, '');
  t = t.replace(/^\[Contexto da aba Tráfego\][\s\S]*?\n\n/i, '');

  return t.replace(/[ \t]+\n/g, '\n').replace(/\n{3,}/g, '\n\n').trim();
}

/** Texto que ainda é ruído interno após a limpeza — não serve de título. */
function pareceRuidoDeTitulo(texto) {
  const t = String(texto || '').trim();
  if (!t) return true;
  // XML/tags internas que sobraram, IDs de task, etc.
  if (/^<\/?[a-z][\w:-]*[\s>]/i.test(t)) return true;
  if (/^task-(?:id|notification)\b/i.test(t)) return true;
  if (/^toolu_/i.test(t)) return true;
  return false;
}

/** Extrai imagens e documentos (PDF/.txt) anexados a uma mensagem do usuário. */
function extrairAnexosDeConteudo(conteudo) {
  if (!Array.isArray(conteudo)) return [];
  const anexos = [];
  for (const b of conteudo) {
    if (!b || !b.source || typeof b.source.data !== 'string') continue;
    if (b.type === 'image' && b.source.type === 'base64') {
      anexos.push({ categoria: 'imagem', mediaType: b.source.media_type || 'image/png', data: b.source.data });
    } else if (b.type === 'document') {
      const categoria = b.source.media_type === 'application/pdf' ? 'pdf' : 'texto';
      if (b.source.type === 'base64' || b.source.type === 'text') {
        anexos.push({
          categoria,
          mediaType: b.source.media_type || (categoria === 'pdf' ? 'application/pdf' : 'text/plain'),
          data: b.source.data,
          nome: typeof b.title === 'string' ? b.title : '',
        });
      }
    }
  }
  return anexos;
}

function truncar(texto, max = TITULO_MAX) {
  const t = String(texto || '').replace(/\s+/g, ' ').trim();
  if (!t) return '';
  return t.length > max ? `${t.slice(0, max - 1)}…` : t;
}

/** Lê o JSONL linha a linha; linhas inválidas são ignoradas. */
function lerLinhasJsonl(arquivo) {
  if (!fs.existsSync(arquivo)) return [];
  const bruto = fs.readFileSync(arquivo, 'utf8');
  const saida = [];
  for (const linha of bruto.split('\n')) {
    const limpa = linha.trim();
    if (!limpa) continue;
    try {
      saida.push(JSON.parse(limpa));
    } catch {
      /* formato interno pode variar — ignora ruído */
    }
  }
  return saida;
}

/**
 * A primeira mensagem de cada conversa na interface chega ao CLI prefixada
 * com "/interface" (ver prepararMensagem em chat.socket.js). Por ser um nome
 * de skill registrado, o CLI grava esse turno como slash command reconhecido —
 * <command-name>/interface</command-name> — e não como texto puro; é esse
 * envelope que distingue uma sessão criada pela interface de qualquer outra
 * sessão do Claude Code rodada nesta mesma pasta de projeto (IDE, subagentes,
 * tarefas em background, checagens one-shot de /usage e /context), que também
 * grava seu .jsonl aqui e não deve poluir o histórico do chat.
 */
function pareceSessaoDaInterface(linhas) {
  for (const o of linhas) {
    if (o.isMeta === true) continue;
    if (o.type !== 'user' || !o.message) continue;
    const conteudo = o.message.content;
    const bruto = typeof conteudo === 'string'
      ? conteudo
      : Array.isArray(conteudo)
        ? conteudo.filter((b) => b && b.type === 'text' && typeof b.text === 'string').map((b) => b.text).join('\n')
        : '';
    if (
      /<command-name>\s*\/interface\s*<\/command-name>/i.test(bruto)
      || /^\s*\/interface\b/i.test(bruto)
    ) {
      return true;
    }
  }
  return false;
}

function tituloDeLinhas(linhas, sessaoId) {
  for (let i = linhas.length - 1; i >= 0; i--) {
    const o = linhas[i];
    if (o.type === 'ai-title' && typeof o.aiTitle === 'string' && o.aiTitle.trim()) {
      const limpo = limparTextoTranscricao(o.aiTitle);
      if (limpo && !pareceRuidoDeTitulo(limpo)) return truncar(limpo);
    }
  }
  for (const o of linhas) {
    if (o.isMeta === true) continue;
    if (o.type !== 'user' || !o.message) continue;
    const texto = extrairTextoDeConteudo(o.message.content);
    if (texto && !pareceRuidoDeTitulo(texto)) return truncar(texto);
  }
  return sessaoId.slice(0, 8);
}

/**
 * Últimas sessões do projeto, por mtime do arquivo.
 * @returns {{ id: string, titulo: string, atualizadoEm: string }[]}
 */
function listarSessoes(raiz, { limite = LIMITE_PADRAO } = {}) {
  const dir = dirProjeto(raiz);
  if (!fs.existsSync(dir)) return [];

  let arquivos;
  try {
    arquivos = fs.readdirSync(dir)
      .filter((nome) => nome.endsWith('.jsonl'))
      .map((nome) => {
        const caminho = path.join(dir, nome);
        const st = fs.statSync(caminho);
        return { id: nome.replace(/\.jsonl$/i, ''), caminho, mtime: st.mtimeMs };
      })
      .sort((a, b) => b.mtime - a.mtime);
  } catch {
    return [];
  }

  const max = Math.max(1, Number(limite) || LIMITE_PADRAO);
  const resultado = [];
  for (const { id, caminho, mtime } of arquivos) {
    if (resultado.length >= max) break;

    let linhas;
    try {
      linhas = lerLinhasJsonl(caminho);
    } catch {
      continue;
    }
    if (!pareceSessaoDaInterface(linhas)) continue;

    let titulo = id.slice(0, 8);
    try {
      titulo = tituloDeLinhas(linhas, id);
    } catch {
      /* mantém fallback */
    }
    resultado.push({ id, titulo, atualizadoEm: new Date(mtime).toISOString() });
  }
  return resultado;
}

/**
 * Turnos user/assistant (texto e anexos: imagens, PDF, .txt) para reconstruir a UI.
 * @returns {{ papel: 'usuario'|'assistente', texto: string, anexos?: {categoria: string, mediaType: string, data: string, nome?: string}[] }[]}
 */
function lerTranscricao(raiz, sessaoId) {
  const arquivo = caminhoSessao(raiz, sessaoId);
  if (!fs.existsSync(arquivo)) throw new Error('Sessão não encontrada.');

  const mensagens = [];
  for (const o of lerLinhasJsonl(arquivo)) {
    // Mensagens de sistema / meta do CLI (slash commands locais, etc.)
    if (o.isMeta === true) continue;

    if (o.type === 'user' && o.message) {
      const texto = extrairTextoDeConteudo(o.message.content);
      const anexos = extrairAnexosDeConteudo(o.message.content);
      // Após limpar tags internas, comandos locais ficam vazios — não entram no chat
      if (texto || anexos.length) mensagens.push({ papel: 'usuario', texto, anexos });
    } else if (o.type === 'assistant' && o.message) {
      const texto = extrairTextoDeConteudo(o.message.content);
      if (texto) mensagens.push({ papel: 'assistente', texto });
    }
  }
  return mensagens;
}

/**
 * Apaga o transcript JSONL de uma sessão do Claude CLI.
 * @returns {{ id: string }}
 */
function excluirSessao(raiz, sessaoId) {
  const arquivo = caminhoSessao(raiz, sessaoId);
  if (!fs.existsSync(arquivo)) throw new Error('Sessão não encontrada.');
  fs.unlinkSync(arquivo);
  return { id: String(sessaoId).replace(/[^a-zA-Z0-9_-]/g, '') };
}

module.exports = {
  encodePath,
  dirProjeto,
  listarSessoes,
  lerTranscricao,
  excluirSessao,
  LIMITE_PADRAO,
};
